apiVersion: v1
# k8s 有哪些 volume
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    role: my-local-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/zxnl/Data/code/go-application/webook/tmp"