apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
  labels:
    role: webook-mysql-claim
spec:
  storageClassName: standard
  accessModes:
#    单读写
    - ReadWriteOnce
#    多读一写
#    - ReadOnlyMany
#    多读多写
#    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


  