// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

//func InitWebserver() *gin.Engine {
//	v := ioc.InitHandlerFunc()
//	db := ioc.Initdb()
//	gormUserDAO := dao.NewUserDAO(db)
//	cmdable := ioc.InitRedis()
//	userCache := cache.NewUserCache(cmdable)
//	userRepository := repository.NewUserRepository(gormUserDAO, userCache)
//	userService := service.NewUserService(userRepository)
//	codaCache := cache.NewCodeCache(cmdable)
//	codeRepository := repository.NewCodeRepository(codaCache)
//	smsService := ioc.NewSmsService()
//	codeService := service.NewCodeService(codeRepository, smsService)
//	userHandler := web.NewUserHandler(userService, codeService)
//	engine := ioc.InitGin(v, userHandler)
//	return engine
//}
